"""add team stats model

Revision ID: 13c5335ecbcd
Revises: bca1226e27e8
Create Date: 2025-03-04 00:51:06.121087

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '13c5335ecbcd'
down_revision = 'bca1226e27e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_teams_id', table_name='teams')
    op.drop_index('ix_teams_name', table_name='teams')
    op.drop_table('teams')
    op.drop_index('ix_matches_id', table_name='matches')
    op.drop_table('matches')
    op.drop_index('ix_players_id', table_name='players')
    op.drop_index('ix_players_name', table_name='players')
    op.drop_table('players')
    op.drop_index('ix_groups_id', table_name='groups')
    op.drop_index('ix_groups_name', table_name='groups')
    op.drop_table('groups')
    op.drop_table('team_group')
    op.drop_index('ix_tournaments_id', table_name='tournaments')
    op.drop_index('ix_tournaments_name', table_name='tournaments')
    op.drop_table('tournaments')
    op.drop_index('ix_player_stats_id', table_name='player_stats')
    op.drop_table('player_stats')
    op.drop_index('ix_phases_id', table_name='phases')
    op.drop_index('ix_phases_name', table_name='phases')
    op.drop_table('phases')
    op.drop_index('ix_goals_id', table_name='goals')
    op.drop_table('goals')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goals',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('match_id', sa.INTEGER(), nullable=True),
    sa.Column('player_id', sa.INTEGER(), nullable=True),
    sa.Column('team_id', sa.INTEGER(), nullable=True),
    sa.Column('minute', sa.INTEGER(), nullable=True),
    sa.Column('type', sa.VARCHAR(length=8), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_goals_id', 'goals', ['id'], unique=False)
    op.create_table('phases',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('tournament_id', sa.INTEGER(), nullable=True),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('order', sa.INTEGER(), nullable=True),
    sa.Column('type', sa.VARCHAR(length=11), nullable=True),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_phases_name', 'phases', ['name'], unique=False)
    op.create_index('ix_phases_id', 'phases', ['id'], unique=False)
    op.create_table('player_stats',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('player_id', sa.INTEGER(), nullable=True),
    sa.Column('tournament_id', sa.INTEGER(), nullable=True),
    sa.Column('matches_played', sa.INTEGER(), nullable=True),
    sa.Column('goals_scored', sa.INTEGER(), nullable=True),
    sa.Column('minutes_played', sa.INTEGER(), nullable=True),
    sa.Column('goals_per_match', sa.FLOAT(), nullable=True),
    sa.Column('minutes_per_goal', sa.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_player_stats_id', 'player_stats', ['id'], unique=False)
    op.create_table('tournaments',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('edition', sa.VARCHAR(), nullable=True),
    sa.Column('year', sa.INTEGER(), nullable=True),
    sa.Column('start_date', sa.DATE(), nullable=True),
    sa.Column('end_date', sa.DATE(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('logo_url', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tournaments_name', 'tournaments', ['name'], unique=False)
    op.create_index('ix_tournaments_id', 'tournaments', ['id'], unique=False)
    op.create_table('team_group',
    sa.Column('team_id', sa.INTEGER(), nullable=False),
    sa.Column('group_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('team_id', 'group_id')
    )
    op.create_table('groups',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('phase_id', sa.INTEGER(), nullable=True),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['phase_id'], ['phases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_groups_name', 'groups', ['name'], unique=False)
    op.create_index('ix_groups_id', 'groups', ['id'], unique=False)
    op.create_table('players',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('team_id', sa.INTEGER(), nullable=True),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('number', sa.INTEGER(), nullable=True),
    sa.Column('position', sa.VARCHAR(), nullable=True),
    sa.Column('is_goalkeeper', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_players_name', 'players', ['name'], unique=False)
    op.create_index('ix_players_id', 'players', ['id'], unique=False)
    op.create_table('matches',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('tournament_id', sa.INTEGER(), nullable=True),
    sa.Column('phase_id', sa.INTEGER(), nullable=True),
    sa.Column('group_id', sa.INTEGER(), nullable=True),
    sa.Column('home_team_id', sa.INTEGER(), nullable=True),
    sa.Column('away_team_id', sa.INTEGER(), nullable=True),
    sa.Column('date', sa.DATE(), nullable=True),
    sa.Column('time', sa.TIME(), nullable=True),
    sa.Column('location', sa.VARCHAR(), nullable=True),
    sa.Column('home_score', sa.INTEGER(), nullable=True),
    sa.Column('away_score', sa.INTEGER(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=11), nullable=True),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['phase_id'], ['phases.id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_matches_id', 'matches', ['id'], unique=False)
    op.create_table('teams',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('short_name', sa.VARCHAR(), nullable=True),
    sa.Column('logo_url', sa.VARCHAR(), nullable=True),
    sa.Column('city', sa.VARCHAR(), nullable=True),
    sa.Column('colors', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_teams_name', 'teams', ['name'], unique=False)
    op.create_index('ix_teams_id', 'teams', ['id'], unique=False)
    # ### end Alembic commands ### 