"""Add team_stats table

Revision ID: 7f4e138776cb
Revises: 13c5335ecbcd
Create Date: 2025-03-04 00:57:45.411348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f4e138776cb'
down_revision = '13c5335ecbcd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 